apiVersion: {{ template "apiVersion" . }}
kind: {{ .Values.workloadType }}
metadata:
  name: {{ include "ix-chart.fullname" . }}
  labels:
    {{- include "ix-chart.labels" . | nindent 4 }}
spec:
  {{- if eq (include "workloadIsDeployment" .) "true" }}
    {{ include "deploymentSpec" . | nindent 2 }}
  {{- else if eq (include "workloadIsCronJob" .) "true" }}
  schedule: {{ .Values.cronSpec | quote }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      {{ include "jobSpec" . | nindent 6 }}
  {{- else }}
    {{ include "jobSpec" . | nindent 2 }}
  {{- end }}
